SELECT TIMES AS COUNT,
       AGENTNO AS AGENT_NO,
       A.NAME
FROM
  (SELECT COUNT(*) AS TIMES,
          E.AGENTNO
   FROM WGS_ExtensionPhase E
   LEFT JOIN WGS_MainCDR M ON E.UCID = M.UCID
   WHERE E.ANSWERTIME IS NOT NULL
     AND M.CALLTYPE = 0
     AND E.AGENTNO IS NOT NULL
     AND E.ExtensionNo >= ?
     AND E.ExtensionNo <= ?
     AND M.STARTTIME > TRUNC(SYSDATE)
   GROUP BY E.AGENTNO) T
LEFT JOIN T_Agent A ON A.NO = T.AGENTNO
WHERE ROWNUM <= 3
ORDER BY TIMES DESC